@extends('layouts.dashboard')
@section('title', 'Add Expense - Accounting')
@section('content')
<div class="dashboard-content">
    <div class="page-header"><div class="header-top"><div><h1 class="page-title">Add Expense</h1><p class="page-subtitle">Record a new business expense</p></div></div></div>
    <div class="form-card">
        <form action="{{ route('accounting.expenses.store') }}" method="POST" enctype="multipart/form-data">@csrf
            <div class="form-grid">
                <div class="form-group"><label>Category <span class="required">*</span></label>
                    <select name="category" required><option value="">— Select —</option><option value="Office Supplies" {{ old('category')=='Office Supplies'?'selected':'' }}>Office Supplies</option><option value="Utilities" {{ old('category')=='Utilities'?'selected':'' }}>Utilities</option><option value="Rent" {{ old('category')=='Rent'?'selected':'' }}>Rent</option><option value="Salaries" {{ old('category')=='Salaries'?'selected':'' }}>Salaries</option><option value="Transportation" {{ old('category')=='Transportation'?'selected':'' }}>Transportation</option><option value="Marketing" {{ old('category')=='Marketing'?'selected':'' }}>Marketing</option><option value="Maintenance" {{ old('category')=='Maintenance'?'selected':'' }}>Maintenance</option><option value="Food & Beverage" {{ old('category')=='Food & Beverage'?'selected':'' }}>Food & Beverage</option><option value="Other" {{ old('category')=='Other'?'selected':'' }}>Other</option></select>@error('category')<span class="field-error">{{ $message }}</span>@enderror</div>
                <div class="form-group"><label>Amount (Rs.) <span class="required">*</span></label><input type="number" step="0.01" name="amount" value="{{ old('amount') }}" required>@error('amount')<span class="field-error">{{ $message }}</span>@enderror</div>
                <div class="form-group"><label>Expense Date <span class="required">*</span></label><input type="date" name="expense_date" value="{{ old('expense_date', date('Y-m-d')) }}" required></div>
                <div class="form-group"><label>Payment Method</label><select name="payment_method"><option value="">— Select —</option><option value="cash" {{ old('payment_method')=='cash'?'selected':'' }}>Cash</option><option value="bank" {{ old('payment_method')=='bank'?'selected':'' }}>Bank Transfer</option><option value="cheque" {{ old('payment_method')=='cheque'?'selected':'' }}>Cheque</option><option value="mobile" {{ old('payment_method')=='mobile'?'selected':'' }}>Mobile Banking</option><option value="card" {{ old('payment_method')=='card'?'selected':'' }}>Card Payment</option></select></div>
                <div class="form-group"><label>Reference</label><input type="text" name="reference" value="{{ old('reference') }}"></div>
                <div class="form-group"><label>Supplier</label><select name="supplier_id"><option value="">— None —</option>@foreach($suppliers as $s)<option value="{{ $s->id }}" {{ old('supplier_id')==$s->id?'selected':'' }}>{{ $s->name }}</option>@endforeach</select></div>
                <div class="form-group full-width"><label>Description</label><textarea name="description" rows="2">{{ old('description') }}</textarea>@error('description')<span class="field-error">{{ $message }}</span>@enderror</div>
                <div class="form-group full-width"><label>Notes</label><textarea name="notes" rows="2">{{ old('notes') }}</textarea></div>
                <div class="form-group full-width"><label>Receipt</label><input type="file" name="receipt" accept="image/*,.pdf">@error('receipt')<span class="field-error">{{ $message }}</span>@enderror</div>
            </div>
            <div class="form-actions"><button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save Expense</button><a href="{{ route('accounting.expenses.index') }}" class="btn btn-secondary">Cancel</a></div>
        </form>
    </div>
</div>
<style>.dashboard-content{padding:30px}.page-header{margin-bottom:30px}.header-top{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:20px}.page-title{font-size:var(--fs-2-2);font-weight:700;color:#1a1a2e;margin:0}.page-subtitle{color:#6c757d;margin:5px 0 0 0;font-size:var(--fs-1-3)}.form-card{background:white;border-radius:16px;padding:40px;box-shadow:0 2px 12px rgba(0,0,0,0.06)}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.form-group.full-width{grid-column:1/-1}.form-group{display:flex;flex-direction:column;gap:8px}.form-group label{font-weight:600;color:#1a1a2e;font-size:var(--fs-1-3)}.form-group .required{color:#CD2737}.form-group input,.form-group select,.form-group textarea{padding:10px 14px;border:2px solid #e9ecef;border-radius:8px;font-size:var(--fs-1-4);font-family:'Noto Sans Devanagari',sans-serif;background:#f8f9fa}.form-group input:focus,.form-group select:focus,.form-group textarea:focus{outline:none;border-color:#CD2737;background:white;box-shadow:0 0 0 3px rgba(205,39,55,0.1)}.form-actions{display:flex;gap:16px;padding-top:8px}.field-error{font-size:var(--fs-1-2);color:#CD2737}.btn{padding:10px 22px;border:none;border-radius:8px;font-size:var(--fs-1-4);font-weight:600;cursor:pointer;font-family:'Noto Sans Devanagari',sans-serif;display:inline-flex;align-items:center;gap:6px;text-decoration:none}.btn-primary{background:#CD2737;color:white;box-shadow:0 4px 15px rgba(205,39,55,0.3)}.btn-primary:hover{transform:translateY(-2px);box-shadow:0 6px 20px rgba(205,39,55,0.4)}.btn-secondary{background:#6c757d;color:white}.btn-secondary:hover{background:#5a6268;transform:translateY(-2px)}@media(max-width:768px){.dashboard-content{padding:20px}.form-card{padding:24px}.form-grid{grid-template-columns:1fr}}</style>
@endsection
