@extends('layouts.dashboard')
@section('title', 'Edit Expense - Accounting')
@section('content')
<div class="dashboard-content">
    <div class="page-header"><div class="header-top"><div><h1 class="page-title">Edit Expense</h1><p class="page-subtitle">{{ $expense->expense_number }}</p></div></div></div>
    <div class="form-card">
        <form action="{{ route('accounting.expenses.update', $expense) }}" method="POST" enctype="multipart/form-data">@csrf @method('PUT')
            <div class="form-grid">
                <div class="form-group"><label>Category <span class="required">*</span></label><select name="category" required><option value="Office Supplies" {{ $expense->category=='Office Supplies'?'selected':'' }}>Office Supplies</option><option value="Utilities" {{ $expense->category=='Utilities'?'selected':'' }}>Utilities</option><option value="Rent" {{ $expense->category=='Rent'?'selected':'' }}>Rent</option><option value="Salaries" {{ $expense->category=='Salaries'?'selected':'' }}>Salaries</option><option value="Transportation" {{ $expense->category=='Transportation'?'selected':'' }}>Transportation</option><option value="Marketing" {{ $expense->category=='Marketing'?'selected':'' }}>Marketing</option><option value="Maintenance" {{ $expense->category=='Maintenance'?'selected':'' }}>Maintenance</option><option value="Food & Beverage" {{ $expense->category=='Food & Beverage'?'selected':'' }}>Food & Beverage</option><option value="Other" {{ $expense->category=='Other'?'selected':'' }}>Other</option></select></div>
                <div class="form-group"><label>Amount (Rs.) <span class="required">*</span></label><input type="number" step="0.01" name="amount" value="{{ old('amount', $expense->amount) }}" required></div>
                <div class="form-group"><label>Expense Date</label><input type="date" name="expense_date" value="{{ old('expense_date', $expense->expense_date->format('Y-m-d')) }}" required></div>
                <div class="form-group"><label>Payment Method</label><select name="payment_method"><option value="">— Select —</option><option value="cash" {{ $expense->payment_method=='cash'?'selected':'' }}>Cash</option><option value="bank" {{ $expense->payment_method=='bank'?'selected':'' }}>Bank</option><option value="cheque" {{ $expense->payment_method=='cheque'?'selected':'' }}>Cheque</option><option value="mobile" {{ $expense->payment_method=='mobile'?'selected':'' }}>Mobile</option><option value="card" {{ $expense->payment_method=='card'?'selected':'' }}>Card</option></select></div>
                <div class="form-group"><label>Reference</label><input type="text" name="reference" value="{{ old('reference', $expense->reference) }}"></div>
                <div class="form-group"><label>Supplier</label><select name="supplier_id"><option value="">— None —</option>@foreach($suppliers as $s)<option value="{{ $s->id }}" {{ $expense->supplier_id==$s->id?'selected':'' }}>{{ $s->name }}</option>@endforeach</select></div>
                <div class="form-group full-width"><label>Description</label><textarea name="description" rows="2">{{ old('description', $expense->description) }}</textarea></div>
                <div class="form-group full-width"><label>Notes</label><textarea name="notes" rows="2">{{ old('notes', $expense->notes) }}</textarea></div>
                <div class="form-group full-width"><label>Receipt</label><input type="file" name="receipt" accept="image/*,.pdf">@if($expense->receipt)<p class="hint">Current: <a href="{{ asset('storage/'.$expense->receipt) }}" target="_blank" style="color:#CD2737;">View receipt</a></p>@endif@error('receipt')<span class="field-error">{{ $message }}</span>@enderror</div>
            </div>
            <div class="form-actions"><button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Update Expense</button><a href="{{ route('accounting.expenses.index') }}" class="btn btn-secondary">Cancel</a></div>
        </form>
    </div>
</div>
<style>.dashboard-content{padding:30px}.page-header{margin-bottom:30px}.header-top{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:20px}.page-title{font-size:2.2rem;font-weight:700;color:#1a1a2e;margin:0}.page-subtitle{color:#6c757d;margin:5px 0 0 0;font-size:1.3rem}.form-card{background:white;border-radius:16px;padding:40px;box-shadow:0 2px 12px rgba(0,0,0,0.06)}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.form-group.full-width{grid-column:1/-1}.form-group{display:flex;flex-direction:column;gap:8px}.form-group label{font-weight:600;color:#1a1a2e;font-size:1.3rem}.form-group .required{color:#CD2737}.form-group input,.form-group select,.form-group textarea{padding:10px 14px;border:2px solid #e9ecef;border-radius:8px;font-size:1.4rem;font-family:'Noto Sans Devanagari',sans-serif;background:#f8f9fa}.form-group input:focus,.form-group select:focus,.form-group textarea:focus{outline:none;border-color:#CD2737;background:white;box-shadow:0 0 0 3px rgba(205,39,55,0.1)}.form-actions{display:flex;gap:16px;padding-top:8px}.field-error{font-size:1.2rem;color:#CD2737}.btn{padding:10px 22px;border:none;border-radius:8px;font-size:1.4rem;font-weight:600;cursor:pointer;font-family:'Noto Sans Devanagari',sans-serif;display:inline-flex;align-items:center;gap:6px;text-decoration:none}.btn-primary{background:#CD2737;color:white;box-shadow:0 4px 15px rgba(205,39,55,0.3)}.btn-primary:hover{transform:translateY(-2px);box-shadow:0 6px 20px rgba(205,39,55,0.4)}.btn-secondary{background:#6c757d;color:white}.btn-secondary:hover{background:#5a6268;transform:translateY(-2px)}@media(max-width:768px){.dashboard-content{padding:20px}.form-card{padding:24px}.form-grid{grid-template-columns:1fr}}</style>
@endsection
